DROP USER IF EXISTS 'USERNAME';
CREATE USER 'USERNAME'@'%';
CREATE DATABASE IF NOT EXISTS sites_data_service;
GRANT ALL ON sites_data_service.* TO 'USERNAME'@'%' IDENTIFIED BY 'PASSWORD';
CREATE DATABASE IF NOT EXISTS sites_service;
GRANT ALL ON sites_service.* TO 'USERNAME'@'%' IDENTIFIED BY 'PASSWORD';
