/**
 * Copyright 2020 Tampere University
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.20).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package tuni.sites.api;

import java.util.List;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;
import tuni.sites.model.Layer;
import tuni.sites.model.Sensor;

/**
 * 
 * 
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-06-18T18:28:26.053990+03:00[Europe/Helsinki]")
@Api(value = "layers")
public interface LayersApi {

	/**
	 * 
	 * @param layerId
	 * @return response
	 */
	@ApiOperation(value = "Delete the requested layer and all layers and sensors associated with the layer.", nickname = "deleteLayerById", notes = "", authorizations = { @Authorization(value = "BasicAuth") }, tags = { "layers", })
	@ApiResponses(value = { @ApiResponse(code = 200, message = "Successful operation.") })
	@RequestMapping(value = "/layers/{layerId}", method = RequestMethod.DELETE)
	ResponseEntity<Void> deleteLayerById(@ApiParam(value = "Delete the layer, which has the given id.", required = true) @PathVariable("layerId") Long layerId);

	/**
	 * 
	 * @param layerId
	 * @return response
	 */
	@ApiOperation(value = "Return the layer with the given ID.", nickname = "getLayerById", notes = "", response = Layer.class, responseContainer = "List", authorizations = { @Authorization(value = "BasicAuth") }, tags = { "layers", })
	@ApiResponses(value = { @ApiResponse(code = 200, message = "Successful operation.", response = Layer.class, responseContainer = "List") })
	@RequestMapping(value = "/layers/{layerId}", produces = { "application/json" }, method = RequestMethod.GET)
	ResponseEntity<List<Layer>> getLayerById(@ApiParam(value = "return the site, which has the given id.", required = true) @PathVariable("layerId") Long layerId);

	/**
	 * 
	 * @param layerId
	 * @param maxResults
	 * @param startPage
	 * @return response
	 */
	@ApiOperation(value = "Return all known layers the user has access to.", nickname = "getLayers", notes = "", response = Layer.class, responseContainer = "List", authorizations = { @Authorization(value = "BasicAuth") }, tags = { "layers", })
	@ApiResponses(value = { @ApiResponse(code = 200, message = "Successful operation.", response = Layer.class, responseContainer = "List") })
	@RequestMapping(value = "/layers/{layerId}/layers", produces = { "application/json" }, method = RequestMethod.GET)
	ResponseEntity<List<Layer>> getLayers(@ApiParam(value = "return the layer, which has the given id.", required = true) @PathVariable("layerId") Long layerId, @ApiParam(value = "Return specified maximum number of results (>=1).") @Valid @RequestParam(value = "max_results", required = false) Integer maxResults, @ApiParam(value = "Start listing from the given page (>=0).") @Valid @RequestParam(value = "start_page", required = false) Integer startPage);

	/**
	 * 
	 * @param layerId
	 * @param maxResults
	 * @param startPage
	 * @return response
	 */
	@ApiOperation(value = "Return all known sensors the user has access to.", nickname = "getSensors", notes = "", response = Sensor.class, responseContainer = "List", authorizations = { @Authorization(value = "BasicAuth") }, tags = { "layers", })
	@ApiResponses(value = { @ApiResponse(code = 200, message = "Successful operation.", response = Sensor.class, responseContainer = "List") })
	@RequestMapping(value = "/layers/{layerId}/sensors", produces = { "application/json" }, method = RequestMethod.GET)
	ResponseEntity<List<Sensor>> getSensors(@ApiParam(value = "return the layer, which has the given id.", required = true) @PathVariable("layerId") Long layerId, @ApiParam(value = "Return specified maximum number of results (>=1).") @Valid @RequestParam(value = "max_results", required = false) Integer maxResults, @ApiParam(value = "Start listing from the given page (>=0).") @Valid @RequestParam(value = "start_page", required = false) Integer startPage);

	/**
	 * 
	 * @param body
	 * @param layerId
	 * @return response
	 */
	@ApiOperation(value = "Create a new layer.", nickname = "postLayer", notes = "", response = Layer.class, responseContainer = "List", authorizations = { @Authorization(value = "BasicAuth") }, tags = { "layers", })
	@ApiResponses(value = { @ApiResponse(code = 200, message = "Successful operation.", response = Layer.class, responseContainer = "List") })
	@RequestMapping(value = "/layers/{layerId}/layers", produces = { "application/json" }, consumes = { "application/json" }, method = RequestMethod.POST)
	ResponseEntity<List<Layer>> postLayer(@ApiParam(value = "The layer to create as an HTTP body.", required = true) @Valid @RequestBody Layer body, @ApiParam(value = "Update the layer, which has the given id.", required = true) @PathVariable("layerId") Long layerId);

	/**
	 * 
	 * @param body
	 * @param layerId
	 * @return response
	 */
	@ApiOperation(value = "Create a new sensor.", nickname = "postSensor", notes = "", response = Sensor.class, responseContainer = "List", authorizations = { @Authorization(value = "BasicAuth") }, tags = { "layers", })
	@ApiResponses(value = { @ApiResponse(code = 200, message = "Successful operation.", response = Sensor.class, responseContainer = "List") })
	@RequestMapping(value = "/layers/{layerId}/sensors", produces = { "application/json" }, consumes = { "application/json" }, method = RequestMethod.POST)
	ResponseEntity<List<Sensor>> postSensor(@ApiParam(value = "The sensor to create as an HTTP body.", required = true) @Valid @RequestBody Sensor body, @ApiParam(value = "Update the layer, which has the given id.", required = true) @PathVariable("layerId") Long layerId);

	/**
	 * 
	 * @param body
	 * @param layerId
	 * @return response
	 */
	@ApiOperation(value = "Update data for an existing layer.", nickname = "putLayerById", notes = "", authorizations = { @Authorization(value = "BasicAuth") }, tags = { "layers", })
	@ApiResponses(value = { @ApiResponse(code = 200, message = "Successful operation.") })
	@RequestMapping(value = "/layers/{layerId}", consumes = { "application/json" }, method = RequestMethod.PUT)
	ResponseEntity<Void> putLayerById(@ApiParam(value = "The updated layer data as an HTTP body.", required = true) @Valid @RequestBody Layer body, @ApiParam(value = "Update layer, which has the given id.", required = true) @PathVariable("layerId") Long layerId);

}
