/**
 * Copyright 2020 Tampere University
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.20).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package tuni.sites.api;

import java.util.List;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Authorization;
import tuni.sites.model.Layer;
import tuni.sites.model.Site;

/**
 * 
 * 
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-06-18T18:21:36.637143+03:00[Europe/Helsinki]")
@Api(value = "sites")
public interface SitesApi {

	/**
	 * 
	 * @param siteId
	 * @return response
	 */
	@ApiOperation(value = "Delete the requested site and all layers and levels associated with the site.", nickname = "deleteSiteById", notes = "", authorizations = { @Authorization(value = "BasicAuth") }, tags = { "sites", })
	@ApiResponses(value = { @ApiResponse(code = 200, message = "Successful operation.") })
	@RequestMapping(value = "/sites/{siteId}", method = RequestMethod.DELETE)
	ResponseEntity<Void> deleteSiteById(@ApiParam(value = "Delete the site, which has the given id.", required = true) @PathVariable("siteId") Long siteId);

	/**
	 * 
	 * @param siteId
	 * @param maxResults
	 * @param startPage
	 * @return response
	 */
	@ApiOperation(value = "Return all known layers the user has access to.", nickname = "getLayers", notes = "", response = Layer.class, responseContainer = "List", authorizations = { @Authorization(value = "BasicAuth") }, tags = { "sites", })
	@ApiResponses(value = { @ApiResponse(code = 200, message = "Successful operation.", response = Layer.class, responseContainer = "List") })
	@RequestMapping(value = "/sites/{siteId}/layers", produces = { "application/json" }, method = RequestMethod.GET)
	ResponseEntity<List<Layer>> getLayers(@ApiParam(value = "return the site, which has the given id.", required = true) @PathVariable("siteId") Long siteId, @ApiParam(value = "Return specified maximum number of results (>=1).") @Valid @RequestParam(value = "max_results", required = false) Integer maxResults, @ApiParam(value = "Start listing from the given page (>=0).") @Valid @RequestParam(value = "start_page", required = false) Integer startPage);
	
	/**
	 * 
	 * @param siteId
	 * @return response
	 */
	@ApiOperation(value = "Return the requested site.", nickname = "getSiteById", notes = "", response = Site.class, responseContainer = "List", authorizations = { @Authorization(value = "BasicAuth") }, tags = { "sites", })
	@ApiResponses(value = { @ApiResponse(code = 200, message = "Successful operation.", response = Site.class, responseContainer = "List") })
	@RequestMapping(value = "/sites/{siteId}", produces = { "application/json" }, method = RequestMethod.GET)
	ResponseEntity<List<Site>> getSiteById(@ApiParam(value = "Return site, which has the given id.", required = true) @PathVariable("siteId") Long siteId);

	/**
	 * 
	 * @param maxResults
	 * @param startPage
	 * @return response
	 */
	@ApiOperation(value = "Return all known sites the user has access to.", nickname = "getSites", notes = "", response = Site.class, responseContainer = "List", authorizations = { @Authorization(value = "BasicAuth") }, tags = { "sites", })
	@ApiResponses(value = { @ApiResponse(code = 200, message = "Successful operation.", response = Site.class, responseContainer = "List") })
	@RequestMapping(value = "/sites", produces = { "application/json" }, method = RequestMethod.GET)
	ResponseEntity<List<Site>> getSites(@ApiParam(value = "Return specified maximum number of results (>=1).") @Valid @RequestParam(value = "max_results", required = false) Integer maxResults, @ApiParam(value = "Start listing from the given page (>=0).") @Valid @RequestParam(value = "start_page", required = false) Integer startPage);

	/**
	 * 
	 * @param body
	 * @param siteId
	 * @return response
	 */
	@ApiOperation(value = "Create a new Layer.", nickname = "postLayer", notes = "", response = Layer.class, responseContainer = "List", authorizations = { @Authorization(value = "BasicAuth") }, tags = { "layers", })
	@ApiResponses(value = { @ApiResponse(code = 200, message = "Successful operation.", response = Layer.class, responseContainer = "List") })
	@RequestMapping(value = "/sites/{siteId}/layers", produces = { "application/json" }, consumes = { "application/json" }, method = RequestMethod.POST)
	ResponseEntity<List<Layer>> postLayer(@ApiParam(value = "The new layer to create as an HTTP body.", required = true) @Valid @RequestBody Layer body, @ApiParam(value = "Update site, which has the given id.", required = true) @PathVariable("siteId") Long siteId);
	
	/**
	 * 
	 * @param body
	 * @return response
	 */
	@ApiOperation(value = "Create a new site.", nickname = "postSite", notes = "", response = Site.class, responseContainer = "List", authorizations = { @Authorization(value = "BasicAuth") }, tags = { "sites", })
	@ApiResponses(value = { @ApiResponse(code = 200, message = "Successful operation.", response = Site.class, responseContainer = "List") })
	@RequestMapping(value = "/sites", produces = { "application/json" }, consumes = { "application/json" }, method = RequestMethod.POST)
	ResponseEntity<List<Site>> postSite(@ApiParam(value = "The site to create as an HTTP body.", required = true) @Valid @RequestBody Site body);

	/**
	 * 
	 * @param body
	 * @param siteId
	 * @return response
	 */
	@ApiOperation(value = "Update data for an existing site.", nickname = "putSiteById", notes = "", authorizations = { @Authorization(value = "BasicAuth") }, tags = { "sites", })
	@ApiResponses(value = { @ApiResponse(code = 200, message = "Successful operation.") })
	@RequestMapping(value = "/sites/{siteId}", consumes = { "application/json" }, method = RequestMethod.PUT)
	ResponseEntity<Void> putSiteById(@ApiParam(value = "The updated site data as an HTTP body.", required = true) @Valid @RequestBody Site body, @ApiParam(value = "Update site, which has the given id.", required = true) @PathVariable("siteId") Long siteId);

}
